<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-S7UJHO9I" failures="1" tests="5" name="Personal loan" time="0.151" errors="0" timestamp="2025-07-29T06:13:47 IST">
  <testcase classname="TestNgTutorial.day1" name="Demo" time="0.038">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNgTutorial.day1.Demo(day1.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="TestNgTutorial.day2" name="ploan" time="0.003"/>
  <testcase classname="TestNgTutorial.day4" name="LoginAPIHomeLoan" time="0.006"/>
  <testcase classname="TestNgTutorial.day4" name="MobileLoginHomeLoan" time="0.002"/>
  <testcase classname="TestNgTutorial.day4" name="WebloginHomeLoan" time="0.004"/>
  <testcase classname="TestNgTutorial.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
